# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

env:
  flutter-version: 3.19.6
  channel: stable

on: [ create, workflow_dispatch ]

jobs:
    build-windows-target:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - name: Flutter Setup
          # You may pin to the exact commit or the version.
          # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
          uses: subosito/flutter-action@v2.14.0
          with:
            # The Flutter version to make available on the path
            flutter-version: ${{ env.flutter-version }}
            # The Flutter build release channel
            channel: ${{ env.channel }}
            # Cache the Flutter SDK
            cache: true
        - name: Disable Flutter telemetry
          run: |
            flutter --disable-analytics
            dart --disable-analytics
        - name: Build Windows target (minimal)
          run: flutter build windows --release --dart-define=profile=minimal
        - name: 'Upload "Minimal" Artifact'
          uses: actions/upload-artifact@v4.3.3
          with:
            name: windows_64_minimal
            path: build/windows/x64/runner/Release
        - name: Download additional dependencies
          shell: bash
          run: ./scripts/get_windows_dependencies.sh
            # mv deps/* build/windows/x64/runner/Release/data/flutter_assets/assets/executables
        - name: Extract ffmpeg and mpv
          shell: pwsh
          run: |
            7z.exe e -odeps .\mpv.7z d3dcompiler_43.dll mpv.com mpv.exe
            7z.exe e -odeps .\ffmpeg.7z ffmpeg.exe -r
        - name: Move dependencies
          shell: pwsh
          run: mv deps/* build/windows/x64/runner/Release/data/flutter_assets/assets/executables
        - name: Build Windows target (full)
          run: flutter build windows --release --dart-define=profile=full
        - name: 'Upload "Full" Artifact'
          uses: actions/upload-artifact@v4.3.3
          with:
            name: windows_64_full
            path: build/windows/x64/runner/Release
            
    build-linux-target:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4

        - name: Flutter Setup
          # You may pin to the exact commit or the version.
          # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
          uses: subosito/flutter-action@v2.14.0
          with:
            # The Flutter version to make available on the path
            flutter-version: ${{ env.flutter-version }}
            # The Flutter build release channel
            channel: ${{ env.channel }}
            # Cache the Flutter SDK
            cache: true
        - name: Disable Flutter telemetry
          run: |
            flutter --disable-analytics
            dart --disable-analytics
        - name: Install build dependencies
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build libgtk-3-dev
        - name: Build Linux target
          run: flutter build linux --release
        
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v4.3.3
          with:
            name: linux_64
            path: build/linux/x64/release/bundle
